[project]
name = "bto-compass"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "langchain>=1.3.18",
    "langchain-groq>=1.1.3",
    "langgraph>=1.2.11",
    "pandas>=3.0.5",
    "pydantic>=2.13.5",
    "pytest>=9.1.1",
    "python-dotenv>=1.2.3",
    "scikit-learn>=1.9.0",
    "streamlit>=1.62.0",
]

[project.scripts]
bto-compass = "bto_compass:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
